/**
 * OpenAPI codegen — pulls the FastAPI spec and emits typed schema.
 *
 * Usage:
 *   pnpm gen:api                       # against http://localhost:8000
 *   API_URL=https://api.reflow.app pnpm gen:api
 *
 * Output: src/api/generated/schema.d.ts (committed)
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import openapiTS, { astToString } from "openapi-typescript";

const API_URL = process.env.API_URL ?? "http://localhost:8000";
const SPEC_URL = `${API_URL}/openapi.json`;
const OUT_DIR = path.resolve("src/api/generated");
const OUT_FILE = path.join(OUT_DIR, "schema.d.ts");

async function main(): Promise<void> {
  console.log(`Fetching OpenAPI spec from ${SPEC_URL}...`);
  const ast = await openapiTS(new URL(SPEC_URL), {
    additionalProperties: false,
    alphabetize: true,
    defaultNonNullable: true,
  });
  const contents = astToString(ast);

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(
    OUT_FILE,
    `/* eslint-disable */\n// Auto-generated by scripts/generate-api.ts — do not edit by hand.\n\n${contents}`,
    "utf-8",
  );
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
